apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ha-proxy
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
    - group: apps
      kind: StatefulSet
      jsonPointers:
        - /spec/replicas
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: haproxy
    targetRevision: 4.0.7
    helm:
      values: |
        service:
          type: ClusterIP
          ports:
            - port: 8080
              targetPort: 8080
              name: postgres

        replicaCount: 2

        resources:
          requests:
            cpu: 100m
            memory: 128Mi

          limits:
            cpu: 500m
            memory: 512Mi
          
        pdb:
          minAvailable: 1

        configuration: |
          global
            log stdout format raw local0
            maxconn 1024
          defaults
            mode tcp # added
            log global
            retries 3 # added
            timeout client 5m
            timeout connect 10s
            timeout server 5m
            option tcplog    # added
          frontend postgres
            bind *:8080
            default_backend postgres_backend
          backend postgres_backend
            mode tcp # added
            option tcp-check # added
            default-server inter 5s fall 3 rise 2 # added
            server postgres test-server-pgsql.postgres.database.azure.com:5432 check
        
        httpRoute:
          enabled: false
          annotations: {}
          labels: {}
          parentRefs:
            - group: gateway.networking.k8s.io	
              kind: Gateway
              name: ai-gateway-private
              sectionName: http
              namespace: default
          hostnames:
            - postgres.skanth.test
          matches:
            - path:
                type: PathPrefix
                value: /
          backendRefs:
            - group: ''
              kind: Service
              name: ha-proxy-haproxy
              port: 80       
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true # Better for CRDs


                             
# kubectl delete crds authenticationfilters.gateway.nginx.org backendtlspolicies.gateway.networking.k8s.io clientsettingspolicies.gateway.nginx.org gatewayclasses.gateway.networking.k8s.io gateways.gateway.networking.k8s.io grpcroutes.gateway.networking.k8s.io httproutes.gateway.networking.k8s.io listenersets.gateway.networking.k8s.io nginxgateways.gateway.nginx.org nginxproxies.gateway.nginx.org observabilitypolicies.gateway.nginx.org proxysettingspolicies.gateway.nginx.org ratelimitpolicies.gateway.nginx.org referencegrants.gateway.networking.k8s.io snippetsfilters.gateway.nginx.org snippetspolicies.gateway.nginx.org tlsroutes.gateway.networking.k8s.io upstreamsettingspolicies.gateway.nginx.org wafpolicies.gateway.nginx.org