name: storage-service

on:
  workflow_dispatch: 
  push:
    branches: [ main ]
#   pull_request:
#     branches: [ main ]
    paths:
    - 'docuflow/storage-service/**'


permissions:
  contents: write
  
env:
  IMAGE_TAG: ${{ github.sha }}

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.11' 

  gitleaks-scan:
    runs-on: ubuntu-latest
    needs: compile
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      # - name: Gitleaks Setup
      #   uses: gitleaks/gitleaks-action@v2

      # - name: Gitleaks Scan
      #   run: |
      #     gitleaks detect --source ./backend --exit-code 1
  # sonar-backend:
  #   runs-on: ubuntu-latest
  #   needs: gitleaks-scan
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v6

#       - name: SonarQube Scan (client)
#         uses: SonarSource/sonarqube-scan-action@v6
#         with:
#           projectBaseDir: backend        # 👈 instead of working-directory
#           args: >
#             -Dsonar.organization=openai
#             -Dsonar.projectKey=openai_backend
#             -Dsonar.projectName=openai_backend
#             -Dsonar.sources=.
#             -Dsonar.python.version=3.11
            
#         env:
#           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
#           SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

#   dependency-check:
#       runs-on: ubuntu-latest
#       needs: sonar-backend
#       steps:
#       - uses: actions/checkout@v4
  
#       - uses: actions/setup-python@v5
#         with:
#           python-version: '3.11'
  
#       - name: Install dependencies
#         run: pip install -r backend/requirements.txt
  
#       - name: Install Snyk CLI
#         run: npm install -g snyk
  
#       - name: Authenticate Snyk
#         run: snyk auth ${{ secrets.SNYK_TOKEN }}
  
#       - name: Monitor dependencies
#         run: snyk monitor --file=backend/requirements.txt --severity-threshold=high

  build_storage_service_docker_image_and_push:
    runs-on: ubuntu-latest
    # needs: dependency-check
    needs: gitleaks-scan
    # permissions:
    #   packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        # with:
          # token: ${{ secrets.PAT_TOKEN }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: srikanthhg
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Docker image (storage-service)
        uses: docker/build-push-action@v6
        with:
          context: ./docuflow/storage-service
          file: ./docuflow/storage-service/Dockerfile
          push: true
          tags: |
            ${{ github.repository_owner }}/storage-service:${{ env.IMAGE_TAG }}
  trivy_image_scan:
    runs-on: ubuntu-latest
    needs:
      - build_storage_service_docker_image_and_push
    steps:
      - name: Checkout (noop, keeps workspace consistent)
        uses: actions/checkout@v4

      - name: Run Trivy image scan for storage-service
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: image
          image-ref: ${{ github.repository_owner }}/storage-service:${{ env.IMAGE_TAG }}
          format: table
          exit-code: '0'
          ignore-unfixed: true
          vuln-type: os,library
          severity: CRITICAL,HIGH
  update-image-tag-in-storage-service-helm-chart:
    runs-on: ubuntu-latest
    needs:
      - trivy_image_scan
    steps:
      - name: Checkout (noop, keeps workspace consistent)
        uses: actions/checkout@v6
       
      - name: Update storage-service image tag
        run: |
          ls -la
          sed -i "s|^\([[:space:]]*tag:[[:space:]]*\).*|\1\"${IMAGE_TAG}\"|" charts/storage-service/values.yaml
          echo "Updated lines:"
          grep -n "tag:" charts/storage-service/values.yaml
      
      - name: Commit and push changes
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          git add charts/storage-service/values.yaml
          git diff --cached --quiet || git commit -m "updated storage-service image tag"
          git push
#   create-helm-chart:
#     runs-on: ubuntu-latest
#     needs:
#       - update-image-tag-in-storage-service-helm-chart
#     steps:
#       - name: Checkout (noop, keeps workspace consistent)
#         uses: actions/checkout@v6

#       - name: Create Helm chart package
#         run: |
#           echo ${{ secrets.PAT_TOKEN }} | helm registry login ghcr.io -u USERNAME --password-stdin
#           helm package charts/storage-service --destination ./helm-packages
#           ls -la ./helm-packages
#           helm push ./helm-packages/storage-service-*.tgz oci://ghcr.io/srikanthhg